### ISSUE TITLE
各種パラメータ調整をGUIで可能にする

### ISSUE THREAD

**Issue by maopotcha** [pwri-opera/OperaSim-PhysX#12]
@yosuke 

以下の機能開発をお願いいたします。

### 概要
- 土砂や建機のパラメータをユーザがGUI上で簡単に調整できるようにする

### 目的
- 様々な作業対象物（土質）に、ユーザ側でシンプル対応可能な形にしたい

### やること
- 土砂（粒子）のサイズ/斥力/引力等に関するパラメータを調整するGUIを用意する
- 建機のアクチュエータ出力や挙動に関するパラメータを調整するGUIを用意する
- 該当するパラメータの選定についても、検討をお願いしたい
- 各パラメータの値域、意味、そのパラメータを変更することによって定性的な変化がどのようになるか等の情報をREADMEに追記する

### その他

**Comment by yosuke** [comment]
バケットと土のインタラクションの設定については、バケットの先にスクリプトがアタッチされているが、深い場所にあるためわかりにくい＆設定項目が足りない。
<img width="1046" alt="スクリーンショット 2023-05-12 10 08 48" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/79a63e89-bcfa-48e6-8780-0f5a7f68b537">
粒子の大きさはPrefabで設定可能。これについてはREADMEに記述されていないことが問題と思われるので追記のみで良いかもしれない。
<img width="423" alt="スクリーンショット 2023-05-12 9 40 25" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/7c743b3c-d672-4e66-a776-f307e89b2455">

**Comment by yosuke** [comment]
アクチュエータ出力の設定に関しては、以下で導入されたJointPosControllerでの対応が必要
https://github.com/pwri-opera/OperaSim-PhysX/commit/a911f1cb873a17dae0c1461bcc59bf02bac16285
FollowJointTrajectoryActionでも同様の処理があるので、そちらも忘れずに。

**Comment by yosuke** [comment]
関節リミットやトルクリミットを規定するX Driveパラメータは、UnityEditorから各関節につき設定できる。
<img width="987" alt="スクリーンショット 2023-05-12 11 21 28" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/e782b403-66e3-40ad-9fd1-6ffec2b5b45d">
ただし、現在はJointPosControllerとFollowJointTrajectoryAction上で上書き設定している。
上書き設定部分を無効化してUnityEditor上からの設定を生かすようにするのが良さそう。
無効化とともに上記をREADMEに追記することで対応。

**Comment by yosuke** [comment]
上記以外だと、PhysicsManagerから設定するDefault Solver Iterationsパラメータが非常に重要。
https://tech.pjin.jp/blog/2017/04/29/unity_physics_physics-manager/
既にUIで設定できるようになっているが、READMEに要追記。

**Comment by yosuke** [comment]
こちらのブランチで作業中。
https://github.com/pwri-opera/OperaSim-PhysX/tree/feature/ui_based_joint_control_parameter
PosControlとTrajectoryActionが共存できるようにする変更も追加。

**Comment by maopotcha** [comment]
ありがとうございます。
UIの形に拘る必要はありませんので、パラメータの調整方法と意味についての解説情報をREADMEに追記いただければ充分です。ある程度の開発単位が完了したら、小まめにPullRequestいただければ幸いです。

**Comment by yosuke** [comment]
粒子シミュレーション部分のUI実装はとりあえず完了。READMEへの追記要。

**Comment by maopotcha** [comment]
@yosuke 
先日、アップデートいただいたSoil Particle SettingsのGUIに表れている以下のパラメータについてREADMEに説明を追記いただけないでしょうか。
Angle of Repose
Repose Jitter
Sync Period
![image](https://github.com/pwri-opera/OperaSim-PhysX/assets/24404939/2f1961e7-97dd-44fe-b695-da05233289df)

**Comment by maopotcha** [comment]
ツールチップに説明を追加したことで、本件クローズとします
https://github.com/pwri-opera/OperaSim-PhysX/issues/50
