### ISSUE TITLE
コリジョンモデルの単純化

### ISSUE THREAD

**Issue by maopotcha** [pwri-opera/OperaSim-PhysX#15]
@yosuke 
以下について、対応をお願いします

### 概要
建機モデルのコリジョンモデルを単純化する

### 目的
シミュレータの計算負荷を低減するため

### やること
- 要否を判断する（労力に対して得られる効果が小さければ、特に必要なし）
- 建機のリンクのコリジョンモデルをシンプルな形状（box, cylinder, sphere等)に置き換える

### その他
- 現状はコリジョンモデルと形状モデルが一致している
- 現段階で特に問題になってはいないので、優先度は低いと考えている

**Comment by yosuke** [comment]
特にバケットやベッセルなどは、土砂粒子との接触計算の高速性が必要なので、下のURLのツールでプリミティブ形状への置き換えを実施済み。この方法を使うと最も干渉計算が早くなる。

https://assetstore.unity.com/packages/tools/sacolliderbuilder-15058

その他、干渉形状については、Convex（凸包）に変換するのが高速化の効果が大きいため、積極的に実施するように設定したい。

ただし、Convex（凸包）を使うと形状の凹んだ部分が埋まるため、関節のハメ合い部分など、隣接リンク間で不要な接触が多く発生するため、下記のAPIを使った隣接リンク間の接触の抑制を先行して実装する必要がある。

https://github.com/pwri-opera/OperaSim-PhysX/issues/18#issuecomment-1584068304
