### ISSUE TITLE
重機同士の干渉が無視されている

### ISSUE THREAD

**Issue by maopotcha** [pwri-opera/OperaSim-PhysX#18]
各重機間の干渉が無視されているために、重機同士がぶつかってもすり抜けてしまう
各リンクオブジェクトのLayer設定が適切に行われていないのが原因と考えられる

Layerを整理して適切に設定することで対策する

**Comment by yosuke** [comment]
ic120については、Default（他オブジェクト）との干渉が無効になっていますね。
<img width="559" alt="スクリーンショット 2023-05-26 15 03 02" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/a1533a15-f4ae-4795-b23a-39c47d3ce30b">

**Comment by yosuke** [comment]
zx200については、各リンクの干渉形状と実際のメッシュへの対応が無くなってしまっている状況。これだと干渉しない。
個々に再設定するのは大変なので、URDFからインポートし直すのが良いかもしれない。

<img width="1482" alt="スクリーンショット 2023-06-09 14 35 49" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/81c1a6ad-0d4e-4151-aff0-a1686734df3d">

**Comment by yosuke** [comment]
c30rについても、vessel_link以外のリンクのcollisionが設定されていない（本来あるはずの部分が無くなっている）。

こちらも再インポートした方が良いかもしれない。

**Comment by yosuke** [comment]
UnityにはGazeboの様な隣接リンク間の自己干渉をオフにする機能がない。

複雑なリンク構造の重機には隣接リンク間の自己干渉のオフは必須だが、レイヤで実現するとレイヤ構造が複座になりそうなため、下のURLのIgnoreCollision APIでプログラム的にオフにするのが良さそう。

https://docs.unity3d.com/ScriptReference/Physics.IgnoreCollision.html

レイヤとしては、できるだけシンプルにし

- 土砂の粒子
- バケット
- その他全て

の3レイヤ程度に整理したい。

**Comment by yosuke** [comment]
以下のコミットでic120のコリジョンモデルを修正＆IgnoreCollisionAPIを使った形に変更。
https://github.com/pwri-opera/OperaSim-PhysX/commit/05bacaac772136078dcf2d2bea9e7a15f6c1a644

ic120とzx120についてはリアルに干渉するようになっている。
<img width="509" alt="スクリーンショット 2023-06-16 17 28 48" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/bdb9d138-d463-42a4-9b0c-a69b947e0332">

**Comment by yosuke** [comment]
zx200を最新のURDF Importerを使ってインポートし直してみた。干渉形状は無事に復活。VHACDオプションを有効にしてインポートすると効率的に凸包形状に分割してくれるので、パフォーマンスも出そう。ただし、バケット部分の形状は少し変形してしまっているので、従来同様に手をかけてプリミティブ変換したほうが良いかもしれない。
<img width="711" alt="スクリーンショット 2023-09-22 9 06 34" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/52c16dfd-2f27-4997-b717-68c33248c97e">

**Comment by yosuke** [comment]
ic120についてはIgnoreCollisionAPIを使って不要な干渉ペアを抑制したが、disable_collisionタグを使った方法も用意されているとのこと。
こちらの方がスマートなので、URDFデータに必要な設定を追加予定。
特にショベルカーの各関節のはめ合いはdisable_collision設定を追加しないと常に干渉した状態になっていると思われる。
https://github.com/Unity-Technologies/Unity-Robotics-Hub/blob/main/tutorials/urdf_importer/urdf_appendix.md#disable-collision-support

**Comment by yosuke** [comment]
ダンプトラックについては、URDFモデルの段階から干渉形状が設定されていない。
SA Mesh Colliderを使ってvisual形状からプリミティブを作ることで干渉形状とする。
<img width="329" alt="スクリーンショット 2023-09-28 13 09 07" src="https://github.com/pwri-opera/OperaSim-PhysX/assets/18067/8305bb04-c233-4840-94ca-f7e361f1ca77">

**Comment by yosuke** [comment]
干渉形状の修正は概ね完了。
まだwheel collider用のdiff drive controllerのパラメーターチューニングが甘いので、調整したのちプルリク作成予定。

**Comment by yosuke** [comment]
@maopotcha 
#30 がマージされて解決したと思うので、issueを閉じます。
問題が再発した場合はreopenするか、新issueを立ててください。
