### ISSUE TITLE
IMUおよびGNSSセンサを追加する

### ISSUE THREAD

**Issue by yosuke** [pwri-opera/OperaSim-PhysX#47]
#13 のサブタスク

### 概要
- 自動化建設機械に用いられる代表的なセンサについて、シミュレータ側から模擬出力をROSメッセージとして出力する機能を付加する

### 目的
- 自律施工ソフトウェアを開発するために、センサシミュレーション機能を追加する
- 手始めとしてIMUとGNSSセンサを追加する

### やること
- GNSSシミュレーション機能 : [Navsatfix型](https://docs.ros2.org/foxy/api/sensor_msgs/msg/NavSatFix.html)
- IMUシミュレーション機能 : [Imu型](https://docs.ros2.org/foxy/api/sensor_msgs/msg/Imu.html)
- UnitySensorsパッケージを使う https://github.com/Field-Robotics-Japan/UnitySensors
- PhysX版シミュレータの4台の重機にそれぞれのセンサを追加する
- センサの追加箇所は実機の位置となるべく一致させる

**Comment by numata-1740** [comment]
ご連絡ありがとうございます

**Comment by numata-1740** [comment]
ご連絡ありがとうございます。
本日、午前中は、昨日の筑波大実験の続きのため
対応できませんでした。
ご依頼のありましたGitHub アカウントをご連絡いたします。
よろしくお願いいたします。

**Comment by numata-1740** [comment]
![IMG_2387](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/6ac15d40-64c5-4031-8abd-c4d2fed16ba6)

**Comment by numata-1740** [comment]
![IMG_2387-1](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/c1e79030-b4a2-4a93-adbe-e073e484e855)
昨日、IMUの設置場所を調べた写真です。zx120　ショベルです

**Comment by numata-1740** [comment]
１）Backet部

**Comment by numata-1740** [comment]
Backet部　
![IMG_2393](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/a7eb390c-b0db-498f-a038-b1a04acb6dc8)
Arm部
![IMG_2394](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/9d440724-37e9-455b-a68a-74c25956c716)
Boom部
![IMG_2395](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/49c25e5a-d55c-4e6b-84e3-9f42aaed5df6)
Base部：操作室横
![IMG_2396](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/e998d21a-bf5a-4878-bf0c-5c9e36f84b7e)

**Comment by numata-1740** [comment]
IMUセンサの型式を調査して、加速度センサの内容を調べる予定です。
設定場所の詳細な位置まで必要でしょうか？
まだ十分な状況を把握していませんので、認識がずれているかもしれませんが
教えてください。よろしくお願いいたします

**Comment by TaroABEJido** [comment]
# zx200 の IMU 配置
zx200 の imu について，配置場所の写真をアップロードします
|![IMG_3732](https://github.com/pwri-opera/OperaSim-PhysX/assets/166089515/93cd48fd-13b0-4851-9443-e0033f70f2ee)|![IMG_3733](https://github.com/pwri-opera/OperaSim-PhysX/assets/166089515/e4c61cff-b27a-473f-960a-b28d1125726d)|![IMG_3734](https://github.com/pwri-opera/OperaSim-PhysX/assets/166089515/8a5728c7-73b5-409f-b0aa-cc97a5238225)|
|---|---|---|

**Comment by TaroABEJido** [comment]
@yosuke 
zx200 について 一通りGNSSとIMUを追加しました
https://github.com/pwri-opera/OperaSim-PhysX/tree/6ed4392ffcceaffafdc51c6acdcdd5fc850aeba1．

以下が主な変更点です．
* body 上に gnss を二基追加
  * GeoCooodinateSysytem もプロジェクトに追加（座標は土研のDXフィールド）
* bucket, arm, boom, body にそれぞれIMU を追加

IMUの正確な配置（特に向き）は分からないので，見た目で適当に配置しています．

**Comment by TaroABEJido** [comment]
# バケットのIMUに関する扱い方
* バケットの IMU に関して 実機に於いてはバケットのリンク？を構成する部品に対して IMU が搭載されているが，現状 Unity 内ショベルには下図のように該当のリンクが存在しないため，実機のIMU をどのように物理シミュレータで再現するかという問題がある．
<img src="https://github.com/pwri-opera/OperaSim-PhysX/assets/166089515/7204bcab-5a48-40ca-ab3e-9315866b1d5c" width="500">

* 実機においては，上記図該当部に設置されたIMUの情報からバケットの関節角度等を幾何学的情報に基づいて算出，Topic として出力している．
* Unity 内ショベルに於いては，バケットリンクにIMUを定義することは可能であるため，幾何学的情報さえあれば実機におけるIMUより計測される姿勢情報は再現可能であるが，加速度や角速度の情報の再現が困難である．

**Comment by yosuke** [comment]
@numata-1740 

- センサの追加箇所は実機の位置と***なるべく***一致させる

ということなので、位置はそこまで厳密でなくて良いです。

**Comment by yosuke** [comment]
@numata-1740 
IMUの型番がわかったら、「データの出力レート」についても可能であれば合わせてください。

**Comment by yosuke** [comment]
@numata-1740 
作業が進んだら、適当なところでgitの`feature/[適当なブランチ名]`ブランチにコミットして、githubにpushしておいてください。

**Comment by numata-1740** [comment]
**ｚｘ１２０のＩＭＵ配置**
大変遅くなり申し訳ありません

IMUセンサとGNSSの取り付け位置を調査した画像により
zx120 について unity ローカルプロジェクトにてGNSSとIMUを追加しました

https://github.com/pwri-opera/OperaSim-PhysX/tree/feature/gnss_imu_numata

以下が主な変更点です．

body 上に gnss を１基追加
GeoCooodinateSysytem もプロジェクトに追加（座標は土研のDXフィールド）
bucket, arm, boom, body にそれぞれIMU を追加
IMUの正確な配置（特に向き）は分からないので、見た目で適当に配置しています．

Github のローカルリポジトリ作成に手間取りました。
今回の修正についてコミットをせず、
ローカルで作成したプロジェクトのUnity データを一括してローカルリポジトリに
アップロードしコミットしています。
まだまだ、トレーニング中ですので何か問題や不具合があれば
ご連絡ください。

**Comment by numata-1740** [comment]
> @numata-1740 IMUの型番がわかったら、「データの出力レート」についても可能であれば合わせてください。
下記の型式となります
出力レートは　：125kbit - 1Mbit/sec となっています。
今回のコミットには反映していませんので、次回のコミットに反映させる予定です。
![NOVATRON-IMU-01-1](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/0f965a95-8b32-47d4-b961-e4506e5d533e)
![NOVATRON-IMU-02-1](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/631ff3d2-7b19-4f16-9625-ac1528e3975c)

**Comment by yosuke** [comment]
@numata-1740 
ブランチは作成されているものの、コミットがありませんでした。
gitのブランチ作成、コミット、githubへのpushは、重要なオペレーションなので練習してできるようになっておいてください。
「IMUのレート」ですが、ビットレートではなく「サンプリングレート」が知りたい＆合わせて欲しいです。

**Comment by numata-1740** [comment]
@yosuke 様

大変遅くなり申し訳ありませんでした

下記に修正したソースファイルをアップロードしました。

https://github.com/pwri-opera/OperaSim-PhysX/tree/gnss_imu_numata

尚、IMUのレートについては反映していません

何か問題や不具合があればご連絡ください。

**Comment by numata-1740** [comment]
@yosuke 様
zx120 ショベルについて
feature/gnss_imu_numata　ブランチにアップロードしました
修正内容：
IMUセンサ：body、boom、arm　を追加しました
また、gnss を追加しました
尚、IMU、gnssのサンプリングレートについては反映していません。
何か問題や不具合があればご連絡ください。

**Comment by numata-1740** [comment]
@yosuke 様
zx120 ショベルについて
トピック名とトピック毎のデータレートを
筑波大学共同研究で取得した実機の bag データファイルから
再生して取得したデータレートをご連絡いたします。

表１．GNSS IMU センサ 通信トピックと通信サンプリングレート調査
No. | 名称 | 部位 | トピック | サンプリングレート[msec] | 備考
-- | -- | -- | -- | -- | --
1 | GNSS |   | gnss_odom | 100 |  
2 | IMU | rotator | g2_imu | 10 |  
3 | IMU | boom | g2_imu | 10 |  
4 | IMU | arm | g2_imu | 10 |  
5 | IMU | bucket | g2_imu | 10 |  

![gnss_rate](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/d8f83ee6-49d4-4547-a28a-c9157e8b9dc4)
![rotator_rate](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/380c0cc9-9906-4522-8464-1c4674edf8ef)
![boom_rate](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/af4914b1-4478-4026-899a-ad1d2ee8fe94)
![arm_rate](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/b780e6ae-b9ca-404b-81ff-bf0a5449b564)
![bucket_rate](https://github.com/pwri-opera/OperaSim-PhysX/assets/165863249/b4a0922e-c829-42c5-9919-ec405c87864d)

よろしくお願いいたします。

**Comment by numata-1740** [comment]
@yosuke 様
zx120 ショベルについて
feature/gnss_imu_numata　ブランチにアップロードしました
修正内容：
トピック名を実機の通信ログに合わせて修正しました
また、IMU、gnssのサンプリングレートについて同様に修正しました。
何か問題や不具合があればご連絡ください。

**Comment by maopotcha** [comment]
本件、バケット用のIMUは課題が残留しておりますがこれは以下で扱うことにしてクローズにします
https://github.com/pwri-opera/OperaSim-PhysX/issues/61
