### ISSUE TITLE
シミュレーション開始時に zx120 の boom リンクが下がる

### ISSUE THREAD

**Issue by TaroABEJido** [pwri-opera/OperaSim-PhysX#69]
### 概要
* シミュレーション開始時に boom リンクが下がり，バケットが地面と干渉してしまう．
* 指令値を与えると，与えられた値まで駆動できる．シミュレーション内初期値の問題か？

**Comment by numata-1740** [comment]
ご参考までに、連絡します。
zx120モデルに限らず、初期設定の位置は、
１）\Assets\Scenes\SampleScene.unity　
２）詳しい場所は失念しましたが、ROS 内のcatkin_ws 内の設定ファイル
に設定されているようです
添付のファイルサンプルをコピーして元のファイルをxxx-sav で名称変更して
コピーファイルをSampleScene.unityに名称変更して使用してみてください
尚、テストする場合は、unity のプロジェクトをバックアップしてからお試しください
[SampleScene.zip](https://github.com/user-attachments/files/17024521/SampleScene.zip)
詳しい変更点は、ファイル比較で抽出してみてください

**Comment by maopotcha** [comment]
@TaroABEJido 
https://github.com/pwri-opera/OperaSim-PhysX/pull/73
これで解決する内容でしょうか。そうであれば、本件はクローズにします。
