### ISSUE TITLE
ROS TCP ConnectorでROS2プロトコルを選択するとコンパイルエラー（Unity Sensors関連）

### ISSUE THREAD

**Issue by maopotcha** [pwri-opera/OperaSim-PhysX#70]
ROSプロトコルセッティングにてROS2を選択するとコンパイルエラーが発生する
エラーメッセージは以下の通り

Library\PackageCache\com.frj.unity-sensors-ros@c33247ddf2\Runtime\Scripts\Serializers\TF\TFMsgSerializer.cs(37,34): error CS1061: 'HeaderMsg' does not contain a definition for 'seq' and no accessible extension method 'seq' accepting a first argument of type 'HeaderMsg' could be found (are you missing a using directive or an assembly reference?)

Library\PackageCache\com.frj.unity-sensors-ros@c33247ddf2\Runtime\Scripts\Serializers\TF\TFMsgSerializer.cs(37,50): error CS1061: 'HeaderMsg' does not contain a definition for 'seq' and no accessible extension method 'seq' accepting a first argument of type 'HeaderMsg' could be found (are you missing a using directive or an assembly reference?)

**Comment by yosuke** [comment]
解決したと思うので、クローズします。
